[
  {
    "center": [
      540,
      2166
    ],
    "kind": "ud",
    "match": "start",
    "module": "gf9578",
    "project": [
      "pd2326"
    ],
    "shooter": 5,
    "size": [
      190,
      190
    ]
  },
  {
    "center": [
      540,
      2166
    ],
    "kind": "ud",
    "match": "start",
    "module": "gsl7002",
    "project": [
      "pd2326"
    ],
    "shooter": 13,
    "size": [
      190,
      190
    ]
  }
]